import { describe, expect, it } from 'vitest';
import {
  CONTRACT_DUE_SOON_DAYS,
  addCalendarDays,
  addCalendarMonths,
  contractAutoGenerateDue,
  contractDueBucket,
  contractDueOnOrBeforeToday,
  contractVisitRollPatch,
  decideCreateContractServiceJob,
  jobFieldsFromContract,
  missContractJobMessage,
  nextServiceDateAfter,
  pickContractJobCreator,
  requireNextServiceDate,
  selectAutoGenerateDueContracts,
  type ContractVisit,
} from './createContractServiceJob';

/** 16:00 Sunday 23 Aug 2026 in Australia/Perth (08:00 UTC). Today in Perth is 23 Aug. */
const now = new Date('2026-08-23T08:00:00.000Z');
const today = '2026-08-23';

function contract(over: Partial<ContractVisit> = {}): ContractVisit {
  return {
    id: 'con-1',
    company_id: 'co-1',
    client_id: 'c1',
    title: 'Annual maintenance',
    description: 'Test and tag switchboard.',
    contract_number: 'CON-001',
    status: 'active',
    end_date: null,
    service_frequency: 'monthly',
    next_service_date: today,
    last_service_date: '2026-07-23',
    auto_generate_jobs: false,
    notes: 'Internal only',
    contract_value: 4400,
    ...over,
  };
}

describe('calendar roll', () => {
  it('adds days on the calendar, not the runtime timezone', () => {
    expect(addCalendarDays('2026-08-23', 1)).toBe('2026-08-24');
    expect(addCalendarDays('2026-08-31', 1)).toBe('2026-09-01');
    expect(addCalendarDays(' 2026-08-23T00:00:00.000Z ', 14)).toBe('2026-09-06');
    expect(addCalendarDays('', 1)).toBeNull();
  });

  it('clamps month-end instead of overflowing into the next month', () => {
    expect(addCalendarMonths('2026-01-31', 1)).toBe('2026-02-28');
    expect(addCalendarMonths('2024-01-31', 1)).toBe('2024-02-29');
    expect(addCalendarMonths('2026-08-23', 1)).toBe('2026-09-23');
    expect(addCalendarMonths('2026-08-23', 12)).toBe('2027-08-23');
  });

  it('rolls by the contract frequency and stops after end_date', () => {
    expect(nextServiceDateAfter('2026-08-23', 'weekly')).toBe('2026-08-30');
    expect(nextServiceDateAfter('2026-08-23', 'fortnightly')).toBe('2026-09-06');
    expect(nextServiceDateAfter('2026-08-23', 'monthly')).toBe('2026-09-23');
    expect(nextServiceDateAfter('2026-08-23', 'quarterly')).toBe('2026-11-23');
    expect(nextServiceDateAfter('2026-08-23', 'semi-annual')).toBe('2027-02-23');
    expect(nextServiceDateAfter('2026-08-23', 'annual')).toBe('2027-08-23');
    expect(nextServiceDateAfter('2026-08-23', 'monthly', '2026-09-01')).toBeNull();
    expect(nextServiceDateAfter('2026-08-23', 'monthly', '2026-09-23')).toBe('2026-09-23');
    expect(nextServiceDateAfter('2026-08-23', 'whenever')).toBeNull();
  });
});

describe('due buckets use Perth today', () => {
  it('treats a date-only next_service_date as overdue / due soon / later', () => {
    expect(contractDueOnOrBeforeToday(today, now)).toBe(true);
    expect(contractDueOnOrBeforeToday('2026-08-22', now)).toBe(true);
    expect(contractDueOnOrBeforeToday('2026-08-24', now)).toBe(false);
    expect(contractDueBucket('2026-08-22', now)).toBe('overdue');
    expect(contractDueBucket(today, now)).toBe('due_soon');
    expect(contractDueBucket('2026-09-06', now)).toBe('due_soon');
    expect(contractDueBucket('2026-09-07', now)).toBe('later');
    expect(contractDueBucket(null, now)).toBe('none');
    expect(CONTRACT_DUE_SOON_DAYS).toBe(14);
  });
});

describe('requireNextServiceDate', () => {
  it('refuses a blank next service date and keeps a calendar day', () => {
    expect(requireNextServiceDate('')).toEqual({ ok: false, message: 'Next service date is required.' });
    expect(requireNextServiceDate(null)).toEqual({ ok: false, message: 'Next service date is required.' });
    expect(requireNextServiceDate('  ')).toEqual({ ok: false, message: 'Next service date is required.' });
    expect(requireNextServiceDate('2026-08-23')).toEqual({ ok: true, nextServiceDate: '2026-08-23' });
    expect(requireNextServiceDate(' 2026-08-23T00:00:00.000Z ')).toEqual({ ok: true, nextServiceDate: '2026-08-23' });
  });
});

describe('decideCreateContractServiceJob', () => {
  it('creates this visit and rolls next_service_date; does not copy contract value as budget', () => {
    const decided = decideCreateContractServiceJob({ contract: contract(), companyId: 'co-1', now });
    expect(decided).toEqual({
      ok: true,
      dueOn: today,
      lastServiceDate: today,
      nextServiceDate: '2026-09-23',
    });
    expect(contractVisitRollPatch(decided as Extract<typeof decided, { ok: true }>)).toEqual({
      last_service_date: today,
      next_service_date: '2026-09-23',
    });
    const fields = jobFieldsFromContract(contract(), '12 Smith St', today);
    expect(fields.client_id).toBe('c1');
    expect(fields.status).toBe('scheduled');
    expect(fields.scheduled_date).toBe(today);
    expect(fields.budget).toBeNull();
    expect(fields.address).toBe('12 Smith St');
    expect(fields.title).toContain('Annual maintenance');
    expect(fields.title).toContain('23 Aug 2026');
    expect(fields.description).toBe('CON-001\nTest and tag switchboard.');
    expect(fields.description).not.toContain('Internal only');
  });

  it('allows booking a future visit without waiting for due day', () => {
    const decided = decideCreateContractServiceJob({
      contract: contract({ next_service_date: '2026-10-01' }),
      companyId: 'co-1',
      now,
    });
    expect(decided.ok).toBe(true);
    if (decided.ok) {
      expect(decided.dueOn).toBe('2026-10-01');
      expect(decided.nextServiceDate).toBe('2026-11-01');
    }
  });

  it('refuses inactive, missing client, missing date, past end, unknown frequency, wrong company', () => {
    expect(decideCreateContractServiceJob({
      contract: contract({ status: 'pending' }),
      companyId: 'co-1',
      now,
    }).ok).toBe(false);
    expect(decideCreateContractServiceJob({
      contract: contract({ client_id: '' }),
      companyId: 'co-1',
      now,
    })).toMatchObject({ blocker: 'no_client' });
    expect(decideCreateContractServiceJob({
      contract: contract({ next_service_date: null }),
      companyId: 'co-1',
      now,
    })).toMatchObject({ blocker: 'no_next_date' });
    expect(decideCreateContractServiceJob({
      contract: contract({ end_date: '2026-08-01' }),
      companyId: 'co-1',
      now,
    })).toMatchObject({ blocker: 'past_end' });
    expect(decideCreateContractServiceJob({
      contract: contract({ service_frequency: 'whenever' }),
      companyId: 'co-1',
      now,
    })).toMatchObject({ blocker: 'unknown_frequency' });
    expect(decideCreateContractServiceJob({
      contract: contract(),
      companyId: 'co-other',
      now,
    })).toMatchObject({ blocker: 'wrong_company' });
    expect(missContractJobMessage('already_rolled')).toMatch(/already created/i);
    expect(missContractJobMessage('no_creator')).toMatch(/no team member/i);
  });

  it('clears next_service_date when the rolled visit is after end_date', () => {
    const decided = decideCreateContractServiceJob({
      contract: contract({ end_date: '2026-09-01' }),
      companyId: 'co-1',
      now,
    });
    expect(decided.ok).toBe(true);
    if (decided.ok) expect(decided.nextServiceDate).toBeNull();
  });

  it('auto-generate only fires for due active contracts with the flag on', () => {
    expect(contractAutoGenerateDue(contract({ auto_generate_jobs: true }), 'co-1', now)).toBe(true);
    expect(contractAutoGenerateDue(contract({ auto_generate_jobs: false }), 'co-1', now)).toBe(false);
    expect(contractAutoGenerateDue(
      contract({ auto_generate_jobs: true, next_service_date: '2026-08-24' }),
      'co-1',
      now,
    )).toBe(false);
    expect(contractAutoGenerateDue(
      contract({ auto_generate_jobs: true, status: 'expired' }),
      'co-1',
      now,
    )).toBe(false);
    expect(selectAutoGenerateDueContracts([
      contract({ auto_generate_jobs: true }),
      contract({ id: 'con-2', auto_generate_jobs: false }),
      contract({ id: 'con-3', auto_generate_jobs: true, next_service_date: '2026-08-24' }),
    ], 'co-1', now).map(c => c.id)).toEqual(['con-1']);
  });
});

describe('pickContractJobCreator', () => {
  it('uses the oldest admin, else the first member, and never invents an id', () => {
    expect(pickContractJobCreator([])).toBeNull();
    expect(pickContractJobCreator(null)).toBeNull();
    expect(pickContractJobCreator([
      { id: 'member-1', role: 'inspector' },
      { id: 'admin-1', role: 'admin' },
      { id: 'admin-2', role: 'admin' },
    ])).toBe('admin-1');
    expect(pickContractJobCreator([
      { id: 'member-1', role: 'member' },
      { id: 'member-2', role: 'inspector' },
    ])).toBe('member-1');
    expect(pickContractJobCreator([{ id: '  ', role: 'admin' }])).toBeNull();
  });
});
