import {
  CloudSun, Bitcoin, Clock, ClipboardList, LayoutTemplate,
  FileText, TrendingUp, Calendar, Activity, DollarSign,
  Gauge, ListTodo, Calculator, Users, Briefcase,
  ShoppingCart, Package, Receipt,
  Bot, Newspaper, Shield, Zap, Wrench, CheckCircle2, Activity,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export interface WidgetDefinition {
  type: string;
  label: string;
  description: string;
  icon: LucideIcon;
  defaultSize: { w: number; h: number };
  minSize: { w: number; h: number };
  maxSize: { w: number; h: number };
  category: 'data' | 'tools' | 'system' | 'fun' | 'intelligence';
  hasConfig?: boolean;
}

export const WIDGET_REGISTRY: WidgetDefinition[] = [
  // System widgets
  {
    type: 'recent_inspections',
    label: 'Recent Inspections',
    description: 'Your latest inspections with status and quick links',
    icon: ClipboardList,
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 5 },
    category: 'system',
  },
  {
    type: 'templates',
    label: 'Templates',
    description: 'Quick-start a new inspection from a template',
    icon: LayoutTemplate,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 5 },
    category: 'system',
  },
  {
    type: 'inspection_stats',
    label: 'Inspection Stats',
    description: 'Total, completed, and in-progress inspection counts',
    icon: Gauge,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'system',
  },
  {
    type: 'pending_reports',
    label: 'Pending Reports',
    description: 'Inspections waiting to be issued',
    icon: FileText,
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 4 },
    category: 'system',
  },
  // Data widgets
  {
    type: 'weather',
    label: 'Weather',
    description: 'Live weather for a city of your choice',
    icon: CloudSun,
    defaultSize: { w: 2, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 4 },
    category: 'data',
    hasConfig: true,
  },
  {
    type: 'bitcoin',
    label: 'Bitcoin Price',
    description: 'Live BTC price in USD',
    icon: Bitcoin,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'data',
  },
  {
    type: 'crypto',
    label: 'Crypto Price',
    description: 'Live price for any cryptocurrency',
    icon: DollarSign,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'data',
    hasConfig: true,
  },
  {
    type: 'stock_market',
    label: 'Market Overview',
    description: 'S&P 500, Nasdaq, and Dow Jones indices',
    icon: TrendingUp,
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 4 },
    category: 'data',
  },
  // Tools
  {
    type: 'clock',
    label: 'Clock',
    description: 'Current time and date',
    icon: Clock,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 1, h: 1 },
    maxSize: { w: 4, h: 3 },
    category: 'tools',
  },
  {
    type: 'calendar',
    label: 'Mini Calendar',
    description: 'Current month with today highlighted',
    icon: Calendar,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 3 },
    maxSize: { w: 5, h: 4 },
    category: 'tools',
  },
  {
    type: 'calculator',
    label: 'Calculator',
    description: 'Quick calculations right on your dashboard',
    icon: Calculator,
    defaultSize: { w: 2, h: 3 },
    minSize: { w: 2, h: 3 },
    maxSize: { w: 3, h: 4 },
    category: 'tools',
  },
  // Fun
  {
    type: 'activity_feed',
    label: 'Activity Feed',
    description: 'Recent activity across your team',
    icon: Activity,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 6, h: 5 },
    category: 'fun',
  },
  {
    type: 'quick_actions',
    label: 'Quick Actions',
    description: 'Shortcuts to start inspections, build templates, etc.',
    icon: ListTodo,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'tools',
  },
  // CRM widgets
  {
    type: 'upcoming_jobs',
    label: 'Upcoming Jobs',
    description: 'Your next scheduled jobs with date and client',
    icon: Briefcase,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 5 },
    category: 'system',
  },
  {
    type: 'client_stats',
    label: 'Client Stats',
    description: 'Total clients and active job counts at a glance',
    icon: Users,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'system',
  },
  {
    type: 'open_pos',
    label: 'Open Purchase Orders',
    description: 'Count and total value of open POs',
    icon: ShoppingCart,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'system',
  },
  {
    type: 'low_stock',
    label: 'Low Stock Alerts',
    description: 'Items at or below reorder level',
    icon: Package,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 5 },
    category: 'system',
  },
  {
    type: 'outstanding_invoices',
    label: 'Outstanding Invoices',
    description: 'Unpaid invoice totals and overdue amounts',
    icon: Receipt,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'system',
  },
  {
    type: 'revenue_overview',
    label: 'Revenue Overview',
    description: 'Total invoiced vs collected this month',
    icon: DollarSign,
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 3 },
    category: 'system',
  },
  // Intelligence widgets
  {
    type: 'ai_agent',
    label: 'AI Agent',
    description: 'Your on-dashboard agent that can take actions, query data, and manage tasks',
    icon: Bot,
    defaultSize: { w: 3, h: 4 },
    minSize: { w: 2, h: 3 },
    maxSize: { w: 5, h: 6 },
    category: 'intelligence',
  },
  {
    type: 'industry_news',
    label: 'Industry News',
    description: 'Live trade and construction industry news feed',
    icon: Newspaper,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 5 },
    category: 'intelligence',
  },
  {
    type: 'compliance_deadlines',
    label: 'Compliance Deadlines',
    description: 'Upcoming and overdue compliance items',
    icon: Shield,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 5 },
    category: 'intelligence',
  },
  {
    type: 'cash_flow',
    label: 'Cash Flow (7d)',
    description: 'Money in vs out this week with net position',
    icon: Zap,
    defaultSize: { w: 2, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 3 },
    category: 'intelligence',
  },
  {
    type: 'kpi_scorecard',
    label: 'KPI Scorecard',
    description: 'Active jobs, inspections today, overdue invoices, stock items',
    icon: Wrench,
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 4 },
    category: 'intelligence',
  },
  {
    type: 'team_activity',
    label: 'Team Activity',
    description: 'What your team is doing right now',
    icon: Users,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 5 },
    category: 'intelligence',
  },
  {
    type: 'agent_reminders',
    label: 'Agent Reminders',
    description: 'Reminders created by the AI agent, with complete buttons',
    icon: CheckCircle2,
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 5, h: 5 },
    category: 'intelligence',
  },
  {
    type: 'agent_activity',
    label: 'Agent Activity',
    description: 'Live log of every action the AI agent has taken',
    icon: Activity,
    defaultSize: { w: 3, h: 4 },
    minSize: { w: 2, h: 3 },
    maxSize: { w: 5, h: 6 },
    category: 'intelligence',
  },
];

export const WIDGET_MAP = new Map(WIDGET_REGISTRY.map(w => [w.type, w]));

export function getWidgetDef(type: string): WidgetDefinition | undefined {
  return WIDGET_MAP.get(type);
}

export const WIDGET_CATEGORIES: { id: string; label: string }[] = [
  { id: 'intelligence', label: 'Intelligence' },
  { id: 'system', label: 'Your App' },
  { id: 'data', label: 'Live Data' },
  { id: 'tools', label: 'Tools' },
  { id: 'fun', label: 'Extras' },
];
